theme = "hugo-theme-stack"
baseURL = "https://0andwild.com/"
title = "0AndWild_log"
defaultContentLanguage = "ko"
hasCJKLanguage = true
languageCode = "ko-KR"
canonifyURLs = false
enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

[pagination]
    pagerSize = 12

[imaging]
    anchor = "Center"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"
    series = "series"

[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS"]

[services]
    [services.googleAnalytics]
        ID = "G-QL6FY3F6WJ"

[related]
    threshold = 0
    toLower = true

    [[related.indices]]
        name = "tags"
        weight = 60

    [[related.indices]]
        name = "categories"
        weight = 70

    [[related.indices]]
        name = "series"
        weight = 90

    [[related.indices]]
        name = "authors"
        weight = 20
