[ko]
    locale = "ko-KR"
    label = "한국어"
    title = "0AndWild_log"
    weight = 1

    [ko.params.sidebar]
        subtitle = "Deep Dive into Backend"

[en]
    locale = "en-US"
    label = "English"
    title = "0AndWild_log"
    weight = 2

    [en.params.sidebar]
        subtitle = "Deep Dive into Backend"
