disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "0AndWild_log"

[params]
  displayName = "🇺🇸 EN"
  isoCode = "en"
  logo = "img/logo.svg"
  rtl = false
  dateFormat = "2006-01-02"

[params.author]
  name = "gunyoung.Park"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

