baseURL = 'https://0AndWild.github.io/'
languageCode = 'en'
title = 'My New Hugo Site'

[params.author]
name = "gunyoung"
image = "img/profile1.jpg"
imageQuality = 96
headline = "Deep Dive into Software Engineering"
bio = "Always curious, always exploring new tech"
links = [
  { github = "https://github.com/0AndWild" },
  { email = "parkky3563@gmail.com" }
]